name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      # This can be removed because we
      # added mocks
      postgres:
        image: postgis/postgis:13-3.4
        env:
          POSTGRES_DB: gis_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >- # Healthcheck options
          --health-cmd "pg_isready -U user -d gis_db"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        env:
          DB_USER: user
          DB_PASSWORD: password
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: gis_db
          REDIS_HOST: localhost
        run: uv run pytest
